# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ComputerUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1415, 953)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(-330, -180, 1791, 1171))
        self.bg.setText("")
        self.bg.setPixmap(QtGui.QPixmap("D:/COMPUTER/G.U.I Material/B.G/Black_Template.jpg"))
        self.bg.setScaledContents(True)
        self.bg.setObjectName("bg")
        self.gui = QtWidgets.QLabel(self.centralwidget)
        self.gui.setGeometry(QtCore.QRect(20, 10, 721, 541))
        self.gui.setStyleSheet("border:3px solid white")
        self.gui.setText("")
        self.gui.setPixmap(QtGui.QPixmap("D:/COMPUTER/G.U.I Material/B.G/Iron_Template_1.gif"))
        self.gui.setScaledContents(True)
        self.gui.setObjectName("gui")
        self.gui_2 = QtWidgets.QLabel(self.centralwidget)
        self.gui_2.setGeometry(QtCore.QRect(760, 20, 651, 241))
        self.gui_2.setStyleSheet("border:3px solid white")
        self.gui_2.setText("")
        self.gui_2.setPixmap(QtGui.QPixmap("D:/COMPUTER/G.U.I Material/ExtraGui/Hero_Template.gif"))
        self.gui_2.setScaledContents(True)
        self.gui_2.setObjectName("gui_2")
        self.gui_3 = QtWidgets.QLabel(self.centralwidget)
        self.gui_3.setGeometry(QtCore.QRect(760, 270, 651, 241))
        self.gui_3.setStyleSheet("border:3px solid white")
        self.gui_3.setText("")
        self.gui_3.setPixmap(QtGui.QPixmap("D:/COMPUTER/G.U.I Material/ExtraGui/initial.gif"))
        self.gui_3.setScaledContents(True)
        self.gui_3.setObjectName("gui_3")
        self.terminal = QtWidgets.QLabel(self.centralwidget)
        self.terminal.setGeometry(QtCore.QRect(20, 580, 1001, 281))
        self.terminal.setStyleSheet("border:3px solid white")
        self.terminal.setText("")
        self.terminal.setPixmap(QtGui.QPixmap("D:/COMPUTER/G.U.I Material/ExtraGui/B.G_Template_1.gif"))
        self.terminal.setScaledContents(True)
        self.terminal.setObjectName("terminal")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1030, 800, 181, 61))
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"font: 24pt \"MS Shell Dlg 2\";\n"
"border:2px solid white\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1210, 800, 181, 61))
        self.pushButton_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"font: 24pt \"MS Shell Dlg 2\";\n"
"border:2px solid white\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(1030, 720, 361, 71))
        self.textBrowser.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border:3px solid white")
        self.textBrowser.setObjectName("textBrowser")
        self.gui_1 = QtWidgets.QLabel(self.centralwidget)
        self.gui_1.setGeometry(QtCore.QRect(1050, 530, 331, 181))
        self.gui_1.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.gui_1.setText("")
        self.gui_1.setPixmap(QtGui.QPixmap("D:/COMPUTER/G.U.I Material/ExtraGui/Earth_Template.gif"))
        self.gui_1.setScaledContents(True)
        self.gui_1.setObjectName("gui_1")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.pushButton_3.setText(_translate("MainWindow", "Close"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
